---

- name: create shell configuration symlinks
  file:
    src: '{{ lmod_install_link }}/init/{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    state: link
    force: yes
  with_items:
    - src: 'profile',
      dest: '{{ lmod_init_bash_path }}'
    - src: 'cshrc'
      dest: '{{ lmod_init_csh_path }}'

...
